---
title: Jesse MacKinnon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mackinnon.jesse@gmail.com
description: Random writings from a film and history nerd.
baseurl: 
url: http://jessemackinnon.com
show_excerpts: true
paginate: 12
permalink: "/:year/:month/:title/"
header_pages:
- about.md
category_path: categories
twitter_username: jessethemac
disqus:
  shortname: jessemackinnon
markdown: kramdown
remote-theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-category-pages
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Rakefile
