---
title: Jesse MacKinnon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: jesse
    comments: true
    excerpt_separator: 
email: mackinnon.jesse@gmail.com
description: Random writings from a film and history nerd.
baseurl: 
url: http://jessemackinnon.com
show_excerpts: true
paginate: 12
permalink: "/:year/:month/:title/"
header_pages:
- about.md
category_path: categories
twitter:
  username: jessethemac
  card: summary
twitter_username: jessethemac
disqus:
  shortname: jessemackinnon
google_analytics: UA-81724116-1
markdown: kramdown
repository: amy-mac/jesse-blog
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-category-pages
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
- Rakefile
